#ifndef DESQLDATABASE_GLOBAL_H
#define DESQLDATABASE_GLOBAL_H

#include <QtCore/qglobal.h>

#ifdef DESQLDATABASE_LIB
# define DESQLDATABASE_EXPORT Q_DECL_EXPORT
#else
# define DESQLDATABASE_EXPORT Q_DECL_IMPORT
#endif

#endif // DESQLDATABASE_GLOBAL_H
